In [22]:
import numpy as np

W1 = np.random.uniform(size=(1,6), low=-1, high=1)
print(W1)
print(np.shape(W1))

X = np.array([[1.,1.,1.,1.,1.,1.], [2.,2.,2.,2.,2.,2.]])
print(X)
print(np.shape(X))

np.einsum('ij,kj', W1, X)

[[-0.1583746   0.43928725 -0.16169968 -0.52871137 -0.45175807  0.1142026 ]]
(1, 6)
[[ 1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.]]
(2, 6)


array([[-0.74705388, -1.49410775]])

In [1]:
%%writefile read_data.py
#%load read_data.py
import pandas as pd
import os
def load_data(filename):
    csv_path = os.path.join(".", filename)
    return pd.read_csv(csv_path)

room_data = load_data('train_data.txt')
room_data.head()

Overwriting read_data.py


In [2]:
#%%writefile plot_data.py
#%load plot_data.py
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
room_data.plot(subplots=True, layout=(2,3), figsize=(12, 8));

Overwriting plot_data.py


In [3]:
#%%writefile preprocess_data.py
# %load preprocess_data.py

from sklearn import preprocessing
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np
import re
room_data.describe()

#attributes = [attr for attr in list(data) if not re.search(attr, r'date|Occupancy')]
# Create a class to select numerical or categorical columns
# since Scikit-Learn doesn't handle DataFrames yet
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

# list of attributes for the DataFrameSelector (pandas to numpy)
room_attrib = [attr for attr in list(room_data) if not re.search(attr, r'date|Occupancy')]
pipeline = Pipeline([
    ('selector', DataFrameSelector(room_attrib)),
    ('std_scaler', StandardScaler()),
])

room_prepared = pipeline.fit_transform(room_data)
print(np.shape(room_prepared))
print(room_prepared[0])
df = pd.DataFrame(room_prepared)
df.plot(subplots=True, layout=(2,3), figsize=(12, 8));

Overwriting preprocess_data.py


In [12]:
#%%writefile mlp_train.py
# %load mlp_train.py
import os as os
import numpy as np
import scipy.io
import scipy.optimize as optimization

N_EPOCH = 100

def mlp_train(*, n_epoch, minibatch_size):
    # data
    # room_with_bias = np.full((len(room_prepared),6),1.0)
    # room_with_bias[:,1:] = room_prepared
    # # shape is (nrow, 6)
    # X = room_with_bias
    # #print(np.shape(X))
    # # use domain -1,1 for teachers so we can use x.w.d<0 for the classification test
    # # shpae is (nrow,1)
    # t = [z if z == 1 else -1 for z in room_data['Occupancy']]
    # #print(np.shape(t))
    # # starting vector of weights
    # w = np.zeros((np.shape(room_with_bias)[1]))
    # perf = []
    # # sweep through the data N_EPOCH times
    # for _ in range(N_EPOCH):
    #      dw, E = dwp(w,t,X)
    #      w += dw
    #      perf.append(1-E)
    # return w, perf
    return 'foo', 'bar'
# invoke main
w_trained, performance = mlp_train(n_epoch=N_EPOCH, minibatch_size=500)

In [5]:
#%%writefile plot_train_perf.py
# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

plt.ylabel(r'$\%\ Classified$')
plt.xlabel('Epoch')
plt.title('Training Sample, % Correct vs Epoch')
plt.plot(performance)

Overwriting plot_train_perf.py


In [8]:
%%writefile mlp_test.py
def mlp_test(w):

test(w_trained)

Writing mlp_test.py
